changelog:
  categories:
    - title: Breaking
      labels:
        - breaking
    - title: Features
      labels:
        - kind: feature
    - title: Fixes
      labels:
        - kind: bug
    - title: Docs
      labels:
        - kind: docs
    - title: CI / Build
      labels:
        - ci
        - build
        - dependencies
  exclude:
    labels:
      - skip-release-notes
